import React, {useEffect} from 'react';
import {console} from "next/dist/compiled/@edge-runtime/primitives/console";
import Head from "next/head";
import Link from "next/link";
import {useRouter} from "next/router";

const Id = ({data}) => {
    const router = useRouter()
    useEffect(() => {
        if(!localStorage.getItem('User')){
            router.push('/Login')
        }
    }, [])
    const handleAddToCart = (product) => {
        const existingEntries = JSON.parse(localStorage.getItem('Products')) || [];

        const productInfo = {
            id : product.id,
            title : product.title,
            image : product.image,
            price : product.price

        }

        existingEntries.push(productInfo)
        localStorage.setItem("Products", JSON.stringify(existingEntries))

    }
    return (
        <>
        <Head>
            <title>{data.title}</title>
            <meta name="description" content="Generated by Big mart" />
            <meta name="viewport" content="width=device-width, initial-scale=1" />

        </Head>
        <div className="hero min-h-screen bg-base-200">
            <div className="hero-content flex-col lg:flex-row-reverse">
                <img src={data.image} className="lg:w-7/12 md:w-10/12 w-full rounded-lg shadow-2xl" />
                <div>
                    <h1 className="text-5xl font-bold">{data.title}</h1>
                    <p className="py-6 text-justify">{data.description}</p>
                    <p className="text-2xl font-bold">${data.price}</p>
                    <button onClick={() => handleAddToCart(data)} className="px-4 py-2 text-1xl font-bold bg-orange-500 text-white rounded rounded-xl">Add To Cart</button>
                    <Link href="/Cart" className="hover:bg-orange-600 px-4 py-3 text-1xl font-bold bg-orange-500 text-white rounded rounded-xl ml-3">Go To Cart</Link>
                </div>
            </div>
        </div>
        </>
    );
};

    export default Id;

  export const getStaticPaths = async () =>{
      const {productList} = await import('@component/data/data.json')
      const allPaths = productList.map((path) => {
          return {
              params: {
                  product: path.title,
                  id: path.id.toString()
              },
          };
      });


      return {
          paths: allPaths,
          fallback: false,
      };
  }

export async function getStaticProps(context) {
    console.log(context);
    const id = context.params.id;
    console.log(context)
    const { productList } = await import('/data/data.json');

    const eventData = productList.find(product => parseInt(id) === product.id);
    console.log("+++", eventData)

    return {
        props: { data: eventData },
    };
}