import Head from 'next/head'

import { Inter } from 'next/font/google'
import HomePageMain from "@component/src/components/Home/HomePageMain";
import {useEffect} from "react";


const inter = Inter({ subsets: ['latin'] })

export default function Home({data, productList}) {
    useEffect(() => {

        if(!localStorage.getItem('Products')){
            const existingEntries = JSON.parse(localStorage.getItem('Products')) || [];
            localStorage.setItem('Products', JSON.stringify(existingEntries))
        }
    }, [])
  return (
    <>
      <Head>
        <title>Big mart</title>
        <meta name="description" content="Generated by Big mart" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />

      </Head>
        <HomePageMain data = {data} productList={productList}></HomePageMain>

    </>
  )
}

export const getServerSideProps = async () => {
    const {sliderInfo, productList} = await import('data/data.json')
    console.log(sliderInfo)
    console.log(productList)
    return{
        props : {
            data : sliderInfo,
            productList : productList
        }
    }
}
